apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-k8s-argocd-root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd # Can be empty
    server: https://kubernetes.default.svc
  source:
    path: applications
    repoURL: https://github.com/Eftychiou/my-k8s-argocd.git
    targetRevision: HEAD
  sources: []
  project: my-k8s
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true
