apiVersion: v2
name: george-traefik
description: Traefik ingress controller and HTTP routes for George App
type: application
version: 0.1.0
appVersion: "3.6.11"
dependencies:
  - name: traefik
    version: 39.0.6
    repository: https://traefik.github.io/charts
