apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-k8s-argocd-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd # Can be empty
    server: https://kubernetes.default.svc
  source:
    path: applications
    repoURL: https://github.com/Eftychiou/my-k8s-argocd.git
    targetRevision: HEAD  
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
