namespace: george-app

backend:
  service:
    port: 80
    targetPort: 5678

frontend:
  service:
    port: 80
    targetPort: 80


istio:
  namespace: istio-system
  host: george.com
  gatewaySelector: ingressgateway
